image: docker:20.10.0

default:
  tags:
    - ai-r
    - docker

stages:
  - release

variables:
  COMPOSE_PROJECT_NAME: ${CI_JOB_ID}

pre:install:
  stage: .pre
  image: node:14-alpine
  script:
    - npm install
  artifacts:
    expire_in: 1 day
    paths:
      - node_modules

release:semantic-release:
  stage: release
  image: node:14-alpine
  before_script:
    - apk add git openssh-client
    - mkdir -pm 0700 ~/.ssh
    - ssh-keyscan gitlab.com >> ~/.ssh/known_hosts
    - ssh-keyscan github.com >> ~/.ssh/known_hosts
    - eval $(ssh-agent -s)
    - echo "${GIT_SSH_PRIVATE_KEY}" | ssh-add -
  script:
    - git checkout "${CI_COMMIT_BRANCH}"
    - git remote add downstream git@github.com:cogment/cogment-dashboard.git
    - git fetch downstream ${CI_COMMIT_BRANCH}
    - git push downstream ${CI_COMMIT_BRANCH}
    - npx semantic-release
    - git pull downstream ${CI_COMMIT_BRANCH}
    - git push git@gitlab.com:ai-r/cogment-dashboard.git ${CI_COMMIT_BRANCH}
    - git fetch downstream --tags
    - git push git@gitlab.com:ai-r/cogment-dashboard.git --tags
  only:
    - main
    - next
    - alpha

release:docker:
  stage: release
  before_script:
    - apk add docker-compose
  script:
    - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
    - docker-compose build metrics dashboard
    - docker-compose push metrics dashboard
  only:
    - main
    - next
    - alpha
