version: '3.7'

services:
  dashboard:
    image: ${COGMENT_DASHBOARD_IMAGE}
    build:
      context: grafana
    ports:
      - 3000:3000
    depends_on:
      - metrics

  metrics:
    image: ${COGMENT_METRICS_IMAGE}
    build:
      context: prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - 9090:9090
    depends_on:
      - cadvisor

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    depends_on:
      - redis

  redis:
    image: redis:latest
    ports:
      - 6379:6379
