{
 "title": "Reward Dashboard",
 "tags": [ "dashboard" ],
 "time": { "from": "2021-02-24T10:29:29.556Z", "to": "2021-02-24T18:29:29.556Z" },
 "panels": [
  {
   "title": "Reward rate by agent instance",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (name) (rate(actor_reward_summation[2m])) / sum by (name) (rate(actor_rewards_count_total[2m]))"
    }
   ]
  },
  {
   "title": "Reward by agent instance",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (name) (actor_reward_summation)"
    }
   ]
  },
  {
   "title": "Reward rate by agent type",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (actor_class) (rate(actor_reward_summation[5m])) / sum by (actor_class) (rate(actor_rewards_count_total[5m]))"
    }
   ]
  },
  {
   "title": "Reward by agent type",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (actor_class) (actor_reward_summation)"
    }
   ]
  },
  {
   "title": "Total Reward",
   "type": "stat",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (name) (actor_reward_summation)",
     "legendFormat": "{{name}}"
    }
   ]
  }
 ]
}