{
 "title": "Agent Performance",
 "tags": [ "dashboard" ],
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Agent decide time",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "rate(actor_decide_processing_seconds_sum[2m]) / rate(actor_decide_processing_seconds_count[2m])",
     "legendFormat": "{{job}} {{name}}"
    }
   ]
  },
  {
   "title": "Decide time by agent type",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (job) (rate(actor_decide_processing_seconds_sum[2m]) / rate(actor_decide_processing_seconds_count[2m]))",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Actor started and ended",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "actor_started_total", "legendFormat": "Started {{job}}" },
    { "expr": "actor_ended_total", "legendFormat": "Ended {{job}}" },
    {
     "expr": "actor_started_total - actor_ended_total",
     "legendFormat": "Running  {{job}}"
    }
   ]
  },
  {
   "title": "Decide time by agent type",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum by (job) (rate(actor_decide_processing_seconds_sum[2m]) / rate(actor_decide_processing_seconds_count[2m]))",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Decide time by agent",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (job, name) (rate(actor_decide_processing_seconds_sum[2m]) / rate(actor_decide_processing_seconds_count[2m]))",
     "legendFormat": "{{job}} {{name}}"
    }
   ]
  }
 ]
}