{
 "title": "Environment",
 "tags": [ "dashboard" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Number of update per trial",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (job) (rate(environment_update_count_per_trial_sum[1m]) / rate(environment_update_count_per_trial_count[1m]))"
    }
   ]
  },
  {
   "title": "Average trial time",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum by (job) (rate(environment_trial_duration_in_second_sum[1m]) / rate(environment_trial_duration_in_second_count[1m]))"
    }
   ]
  },
  {
   "title": "Trial time duration",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (job) (rate(environment_trial_duration_in_second_sum[1m]) / rate(environment_trial_duration_in_second_count[1m]))",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Starting versus Ending Trials",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "environment_trials_started_total - environment_trials_ended_total",
     "legendFormat": "Not ending {{job}}"
    },
    {
     "expr": "environment_trials_started_total",
     "legendFormat": "Started {{job}}"
    },
    { "expr": "environment_trials_ended_total", "legendFormat": "Ended {{job}}" }
   ]
  }
 ]
}