{
 "title": "Reward Dashboard",
 "tags": [ "dashboard" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Rewards stats by  player",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum by (name) (actor_reward_summation)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Reward rate by agent type",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (actor_class) (rate(actor_reward_summation[5m])) / sum by (actor_class) (rate(actor_rewards_count_total[5m]))"
    }
   ]
  },
  {
   "title": "Rewards Gauge by player",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum by (name) (rate(actor_reward_summation[2m])) / sum by (name) (rate(actor_rewards_count_total[2m]))",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Reward rate by agent instance",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (name) (rate(actor_reward_summation[2m])) / sum by (name) (rate(actor_rewards_count_total[2m]))"
    }
   ]
  },
  {
   "title": "Reward by agent type",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (actor_class) (actor_reward_summation)"
    }
   ]
  },
  {
   "title": "Reward by agent instance",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (name) (actor_reward_summation)"
    }
   ]
  }
 ]
}